version: '3.3'
services:

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - mqtt
    volumes:
      - ./mosquitto:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    networks:
      - mqtt
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=America/Denver
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a8017c002f0dec1190bcd5cebd930c07-if00-port0:/dev/ttyACM0

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=xxxxxxxx
      - TZ=America/Denver # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    networks:
      - mqtt
    devices:
      - 'usb-0658_0200-if00:/dev/ttyUSB0'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server

networks:
  mqtt:
