version: '3.3'
services:

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mosquitto:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=America/Denver
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a8017c002f0dec1190bcd5cebd930c07-if00-port0:/dev/ttyACM0
